### ISSUE TITLE
Ou sont ces documents?

### ISSUE THREAD

**Issue by pascalfares** [mohamadsabra/GLG203#4]
31/12/2017 : Création du document PPT "Présentation" à partir de la vidéo .

01/01/2018 : Création du document PPT "Présentation" à partir de la vidéo. DONE

**Comment by mohamadsabra** [comment]
@pascalfares https://github.com/mohamadsabra/GLG203/blob/master/Pr%C3%A9sentation.pptx 
Same document, created over 2 days.
